export const TABLE_ITEMS_MOCK = [
  {
    status: "",
    name: "Иван",
    type: "",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Сергей",
    type: "type",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Петр",
    type: "",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Ivan",
    type: "type",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Petr",
    type: "",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Grisha",
    type: "vm_guest",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Ivan",
    type: "",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Petr",
    type: "vm_guest",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Grisha",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Ivan",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Petr",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Grisha",
    type: "vm_guest",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Ivan",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Petr",
    type: "vm_guest",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Grisha",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Ivan",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Petr",
    type: "vm_host",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
  {
    status: "",
    name: "Grisha",
    type: "vm_guest",
    location: "location",
    unitId: "unitId",
    InvNumber: "InvNumber",
    tags: "tags",
    createDate: "createDate",
    refreshDate: "refreshDate",
    auditDate: "auditDate",
  },
];
